# Generated by Django 4.2.1 on 2023-05-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_purchase_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='registration_date',
            new_name='purchase_date',
        ),
    ]
