# Generated by Django 4.2 on 2023-05-16 18:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_purchase_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дата покупки'),
        ),
    ]
