# Generated by Django 4.2 on 2023-05-16 18:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата покупки'),
        ),
    ]
